### PR TITLE
chore: first phase; data wrangling/cleaning

### PR DESCRIPTION
**Pull request by SofiyahElemide**
The data cleaning team wrangled and assessed the data for further exploration

### CODE REVIEW

**Review by bamidele42 — APPROVED** [review]
Awesome!!! We are set for the Data visualization team

**Review by bamidele42 — APPROVED** [review]
Good work!!!

**Review by bamidele42 — APPROVED** [review]
Bravo Good Job

**Comment by SofiyahElemide** [comment]
Thanks Bamidele

**Review by SoburahE — APPROVED** [review]
Good work, Next team should fork this project to make changes

**Review by SoburahE — APPROVED** [review]
Approved this change.

**Pull request merged**
